package main

import (
	"log"
	"os"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/spf13/viper"
	postgres "gorm.io/driver/postgres"
	"gorm.io/gorm"

	"gin-sass-salon/app/http/controllers"
	"gin-sass-salon/app/models"
	"gin-sass-salon/config"
	"gin-sass-salon/database/seeders"
	"gin-sass-salon/routes"

	_ "gin-sass-salon/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title           Gin SASS Salon API
// @version         1.0
// @description     API untuk aplikasi SASS Salon dengan JWT Authentication
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.email  support@example.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:9001
// @BasePath  /api

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// 1. Muat Konfigurasi (.env)
	config.LoadConfig()

	// 2. Koneksi ke Database PostgreSQL
	db, err := gorm.Open(postgres.Open(config.DSN()), &gorm.Config{
		DisableAutomaticPing: false,
	})

	if err != nil {
		log.Fatalf("❌ Gagal koneksi ke database PostgreSQL: %v", err)
	}

	// Konfigurasi Pool Koneksi
	sqlDB, _ := db.DB()
	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetMaxOpenConns(100)
	sqlDB.SetConnMaxLifetime(time.Hour)

	log.Println("✅ Koneksi Database PostgreSQL berhasil!")

	// 3. Auto Migrate (Migrasi Database)
	err = db.AutoMigrate(&models.User{})
	if err != nil {
		log.Fatalf("❌ Gagal melakukan AutoMigrate: %v", err)
	}
	log.Println("✅ Database migration selesai (Tabel User siap).")

	// 4. Run Seeder jika flag --seed diberikan
	if len(os.Args) > 1 && os.Args[1] == "--seed" {
		log.Println("🌱 Menjalankan seeder...")
		seeders.RunAllSeeders(db)
		log.Println("✅ Seeding selesai!")
		return
	}

	// 5. Inisialisasi Gin Router
	r := gin.Default()

	// 6. Injeksi koneksi DB ke Controller
	controllers.DBConnection = db

	// 7. Setup Route (termasuk Swagger)
	routes.SetupRoutes(r)

	// 8. Jalankan Server
	appPort := viper.GetString("APP_PORT")
	if appPort == "" {
		appPort = "9001"
	}

	log.Printf("🚀 Server berjalan di :%s", appPort)
	log.Printf("📚 Swagger UI: http://localhost:%s/swagger/index.html", appPort)
	log.Printf("📖 API Docs: http://localhost:%s/api", appPort)

	// Jalankan server Gin
	err = r.Run(":" + appPort)
	if err != nil {
		log.Fatalf("❌ Gagal menjalankan server Gin: %v", err)
	}
}